Console.Write("Bведите x1");
int x1 = int.Parse(Console.ReadLine());
Console.Write("Bведите y1");
int y1 = int.Parse(Console.ReadLine());
Console.Write("Введите z1");
int z1 = int.Parse(Console.ReadLine());
Console.Write("Bведите x2");
int x2 = int.Parse(Console.ReadLine());
Console.Write("Bведите y2");
int y2 = int.Parse(Console.ReadLine());
Console.Write("Введите z2");
int z2 = int.Parse(Console.ReadLine());
double Rasstoyanie = Math.Sqrt(Math.Pow( x2 - x1, 2)+ Math.Pow( y2 - y1, 2)+ Math.Pow ( z2 - z1, 2));
Console.WriteLine(Rasstoyanie);
